### ISSUE TITLE
importFile html content 

### ISSUE THREAD

**Issue by Awea** [OscarGodson/EpicEditor#183] opened 2012-09-12 08:37 UTC
I don't know if it's an issue or not but if I try something like this :

``` javascript
editor.importFile('some-file','<h2>Blabla</h2>');
```

It import the html to editor but it interpret it so I have a **h2** title.

**Comment by OscarGodson** [comment] 2012-09-12 08:44
So, you're saying the code above, for you, is creating an actual H2 like:

## Blahbla

and NOT 

`<h2>Blabla</h2>`?

If so, I can't reproduce. This is what I get:

![](https://img.skitch.com/20120912-d5qymt5rwe1ba4wtw1315im6bw.png)

Can you create a JSBin link with a reproducible case?

**Comment by Awea** [comment] 2012-09-12 08:48
I'm using a gem with your editor but I think It's not the latest version of your editor.

**Comment by OscarGodson** [comment] 2012-09-12 08:52
If you're talking about http://rubydoc.info/gems/epiceditor-rails/0.1.0/frames

It's not the latest, but it looks like it's 0.1.0. That's only 1 release difference from master. I also don't see any changes to importFile really in the release notes: https://github.com/OscarGodson/EpicEditor/wiki/Release-Notes

Can you reproduce this on http://epiceditor.com somehow?

**Comment by Awea** [comment] 2012-09-12 09:14
Okey it come from the browser (Firefox 15.0.1), it work well on chrome (21.0.1180.89)

**Comment by OscarGodson** [comment] 2012-09-12 16:13
Awh, yes, this is actually pretty bad it looks like. Even if you type `<h2>test</h2>` it renders it as actual h2 text on refresh. I'll look into hotfixing this.

**Comment by Awea** [comment] 2012-09-12 16:17
Exactly ! I don't know why and I'm curious to know :)

**Comment by OscarGodson** [comment] 2012-09-12 16:18
Well, more than likely it's because Firefox doesn't support the `innerText` method like Chrome, IE, etc, so we have a shim to make it _try_ to act like innerText. This is probably where the error is happening.

**Comment by OscarGodson** [comment] 2012-09-12 16:41
The fix is easy. I need to QA it some more, but all tests are passing and the bug appears to be fixed now and it was in fact something to do with our `innerText` shim (it wasn't converting `<` and `>` back to `&lt;` and `&gt;`). I'll try pushing it up today!

**Comment by OscarGodson** [comment] 2012-09-13 02:57
OK! hotfixed! Please test it out on http://epiceditor.com again and see if you can repro. The version number is now `0.1.1.1`.

I also cherry-picked this into develop as well.

**Closed as completed by OscarGodson** 2012-09-13 02:57 UTC
Labels: Important, Bug, 0.1.1

**Comment by Awea** [comment] 2012-09-13 08:25
It works ! Thanks @OscarGodson :)
