### ISSUE TITLE
Keep indents on newlines

### ISSUE THREAD

**Issue by janlimpens** [OscarGodson/EpicEditor#104] opened 2012-05-11 15:32 UTC
Hitting enter should keep indents

**Comment by OscarGodson** [comment] 2012-05-11 15:35
Dupe of #39

Indeed. This is high up there on the list, but we need to make this more stable and work cross browser better in the public beta coming up soon (only about 9 more tickets) before we start adding editing features, but this should be one of the first editor enhancements we do.

**Comment by janlimpens** [comment] 2012-05-11 15:35
Hitting enter again, should "outdent" by one level. It might also be good to be able to use the tab key to insert 2 spaces, but this might break UI Accessibility guidelines.

**Comment by OscarGodson** [comment] 2012-05-11 15:36
I like that. I'll add that to the original ticket, thanks @janlimpens

**Closed as completed by OscarGodson** 2012-05-11 15:35 UTC
