### ISSUE TITLE
press p opens preview

### ISSUE THREAD

**Issue by romme86** [OscarGodson/EpicEditor#133] opened 2012-06-26 10:48 UTC
when i press the p key the preview mode is open this dosen't permit the p key to be written and other keys they don't work somtimes, like the o key.

**Comment by OscarGodson** [comment] 2012-06-26 14:53
This sounds like #127. Does #127 sound like your issue? Someone else has reported this as well as me, but I'm having a really hard time trying to reproduce it. Can you reproduce it reliably with a set of steps?

**Comment by romme86** [comment] 2012-06-26 15:19
Yes that also happends. it all works fine until i use the '#' if i press the 'p' after '#' it starts a lot of strange things.

**Comment by OscarGodson** [comment] 2012-06-26 15:26
Hmm, can't repro it that way (or else I wouldn't have been able to write my EpicEditor's docs). I tried in Mac FF and Chrome. What OS and browser are you on?

**Comment by romme86** [comment] 2012-06-26 15:56
win7 firefox :)

**Comment by OscarGodson** [comment] 2012-06-26 15:59
Awesome. That's explain it. I'll look into it some more on Win7 then.

**Comment by OscarGodson** [comment] 2012-06-27 04:48
@romme86 - good news, I was able to reproduce it very easily on FF on Win7. This will probably help with figuring it out for the less easily reproducible cases on other OSs and browsers. I'm working on it now.

**Comment by romme86** [comment] 2012-06-27 07:28
Thank you! i would like to give an help, but i'm kind of a rookie at the moment! :)

**Comment by OscarGodson** [comment] 2012-06-27 15:00
@romme86 I think I came up with an OK fix. Not sure if I can do anything better since Windows binds the alt press to trigger the action menu (File, Edit, etc). My fix is to reset the modifier key value after each successful shortcut. So, once you press `alt+p`, `alt` is reset back to false, meaning it wont get stuck. The only downfall is you can't do `alt+p o` which would preview then open for editing again back to back without having to repress `alt`.

Let me know if this works for you. It's in develop now.

**Comment by johnmdonahue** [comment] 2012-06-28 03:03
@OscarGodson: Ha. I didn't realize you already closed this, but I finally got a chance to play with it on a windows box and came to the exact same conclusion (i.e. set `isMod = false` on successful combo). Seems like a reasonable fix IMO since EE only makes view shortcuts customizable and not other commands you might want to keep pressing (cmd+z etc). Sorry for being late to the party but +1 ;)

**Comment by romme86** [comment] 2012-06-30 17:44
@OscarGodson : hi! i tried with the develop files, but maybe i used the wrong ones because the alt key still gets stuck, but only the first time.. it's a bit better.

**Comment by OscarGodson** [comment] 2012-06-30 21:32
Maybe @johnmdonahue or @dadambickford can try to reproduce off develop on Win7 + Firefox but I can't at all anymore.

It shouldn't get stuck just once tho. If it gets stuck it should keep getting stuck since you're taking the same steps. Strange... 

As long as you did:

``` bash
$ git checkout develop
$ git pull origin develop
```

You should have it. You can also do git log and make sure the `af397d4` sha is there. Should be the 4th down about. If that's there and you're still having problems could you give me the exact steps you're doing? It'd be awesome if you could do a screencast if possible, but if not just refresh the page, and write down the exact steps to get this to happen.

Thanks!

**Comment by romme86** [comment] 2012-07-01 13:04
I'm not good using the shell with git.. but on the website when i click on the pull request says that the OscarGodson:develop is updated with the romme86:develop. is this ok if i use those files?

Anyway the things i do are simply:
-click on the epiceditor.
-press alt+# to print "#"
-press p
-the editor goes in preview mode
-press on the eye icon
-the editor goes in edit mode
now i can print the p key but if i press again alt the issue starts again.

I'm sorry for my lack of knowledge of the shell/bash
hope this is helpfoul.

**Comment by OscarGodson** [comment] 2012-07-01 15:40
@romme86 Thanks, this makes sense now. No worries about the cloning and stuff. Your steps allowed me to reproduce it.

My fix only works for when you press the alt key and then press a shortcut key. I'll add another snippet that looks if the alt key is pressed and another key was pressed that is _not_ a shortcut key. This way it'll reset after every key combination whether it's a shortcut or not.

I'm curious tho, why are you pressing `alt+#`? That doesn't type anything for me. To get a `#` character shouldn't you have to use `shift+3`?

**Closed as completed** 2012-07-01 18:28 UTC
Labels: Important, Bug, 0.1.1

**Comment by OscarGodson** [comment] 2012-07-01 18:29
OK @romme86 I rewrote my fix and now `alt+#` then `p` no longer triggers the previewer. Can you try develop again?

**Comment by romme86** [comment] 2012-07-02 06:48
@OscarGodson hi! i press alt+# because i have the italian keyboard layout, in the us layout the # is over the 3 in my layout it's near the à.
i'll try it again soon i'll let you know!
