### ISSUE TITLE
Alt + s inserts ś every second time

### ISSUE THREAD

**Issue by Cosiek** [OscarGodson/EpicEditor#294] opened 2013-10-03 12:50 UTC
Hi.
I live in Poland and we have this letter "ś", which is written by pressing right alt+s. I noticed that ś is written only every second time.
To be more precise:
if i press(and hold) alt and press s - I get nothing
if i press(and hold) alt and press s twice - I get ś
if i press(and hold) alt and press s three times - I get śś.
if i press(and hold) alt and press o then s  - I get ó
if i press(and hold) alt and press o then s twice - I get óś

This happens on windows 7 (tested of firefox and chrome),
but doesn't happen on Debian (chromium).

I've seen You had similar issue before:
https://github.com/OscarGodson/EpicEditor/issues/144
,but ó works fine.

Thanks.

**Comment by OscarGodson** [comment] 2013-10-03 15:18
alt+s saves. I'd probably suggest what I did with him, if you expect more polish users than other disable or change the alt+s shortcut. I'll think about it some more but not sure if there's any fix without a manual setting for localization which wouldn't be much different then changing the shortcut yourself. If you have suggestions let me know :)

**Comment by Cosiek** [comment] 2013-10-04 07:17
For all I know it's ctrl+s that saves, not alt+s.
I can see in your code that You catch ctrl+s and make it do nothing to prevent save site - quite nice. I tried to turn that catch off - and to my surprise it helped with my ś problem.
The question remains - why `if (isCtrl === true && e.keyCode == 83)` is true for alt+s.

S-based letters seem to be quite common (Poland, Czech, Slovakia, Croatia and probably few more). Unicode character table has four, but some are used in more then one country. I'm quite surprised to be the first to report on this.

**Comment by OscarGodson** [comment] 2013-10-04 08:36
I believe you have a different keyboard layout. I'm guessing that maybe the keycodes are different? I also can't reproduce it on my keyboard. On Mac If I press alt+s twice I get `ßß`, or once, `ß` (same as all textareas). On Windows I get the error beep noise and it types nothing. This happens on all apps and web sites. It's hard for me to test or fix tho because I don't have your keyboard and I'm guessing maybe your Windows version affects this too. 

I might need to wait for someone that has this issue that can send a PR. You're welcome to as well. As long as it doesn't break existing functionality, just extends it for other keyboards, I'm happy to take your word for it. Just not sure how to test :(

**Comment by Cosiek** [comment] 2013-10-09 18:59
I tried to use `console.log(e.keyCode)` on the problem and it turns out that my alt key produces two keypress events - one with keycode=17 (ctrl) then another with keycode=18 (alt).

Well - it turns out I was not precise enough about this key. Its a right alt key - "alt gr". I've found the answer here: http://en.wikipedia.org/wiki/AltGr_key#Control_.2B_Alt_as_a_substitute

My suggestion to solving this is for the alt key to set isCtrl to false.
`if (e.keyCode == 18) { isCtrl = false }`
This solves my ś problem, keeps your default ctrl+s functionality, and it doesn't seem to brake anything (at least nothing I can think of).

**Comment by OscarGodson** [comment] 2013-10-09 19:01
Do you wanna send a PR so you're considered a contributor? If not it's totally fine and I can add this and test it, but just checking :)

**Comment by Cosiek** [comment] 2013-10-09 19:09
You go ahead. :smile:

**Comment by OscarGodson** [comment] 2013-10-15 03:04
OK, this should be fixed then :) let me know if it doesn't work

**Closed as completed by OscarGodson** 2013-10-15 03:04 UTC
Labels: Bug, 0.2.3

**Comment by nder** [comment] 2014-01-07 09:38
@OscarGodson, I don't see any open issues for version 0.2.3 and there is even 1 issue closed for version 0.3.0. Maybe it's time to publish [new release](https://github.com/OscarGodson/EpicEditor/releases)? Don't make all that bugfixes wait in the garage :)

**Comment by OscarGodson** [comment] 2014-01-07 19:15
@nder totally. Only issue is unfortunately I haven't had time to fully test all these fixes. I don't like pushing out fixes without going through all the closed tickets for a release and checking them, and the tests, in IE9, 10, Chrome, and Firefox. If you want to QA each of the closed tickets in those browsers and run the tests and mark them as verified (just comment) I'll trust you :)
