### ISSUE TITLE
In FireFox 14.0.1, iframes can get pushed offscreen if an odd number of pixels are in the viewing area.

### ISSUE THREAD

**Issue by philipaconrad** [OscarGodson/EpicEditor#170] opened 2012-08-11 06:16 UTC
FireFox 14.0.1 rounds all iframe sizes up to the nearest full pixel it seems.

This means that if a user has an odd number of pixels inside the browser viewing area, it will result in a fractional window size, like **733.5px;**. As a result of the round up, one iframe will push the other out of the viewable area, below where people can see it.

If there is a way to forcibly round iframe sizes down to the nearest whole pixel, that might solve the issue.

**Comment by OscarGodson** [comment] 2012-08-11 06:33
Interesting. Do you have an example of this I can see?

**Comment by philipaconrad** [comment] 2012-08-11 06:44
If you have Firefox 14.0.1, you can just resize your browser window until it occurs.

If you like, I can post "before odd-pixel resize" and "after odd-pixel resize" pictures for you.

**Comment by OscarGodson** [comment] 2012-08-11 06:56
Is it reproducible for you on http://epiceditor.com ? I can't repro it there anyway on the same FF version. Is it only fluid width editors?

**Comment by OscarGodson** [comment] 2012-08-11 06:58
I'm probably just missing it, but I can't see any weirdness on my side for fluid width containers too: http://jsbin.com/owirij/3

**Comment by philipaconrad** [comment] 2012-08-11 07:14
I'm able to reproduce it when EpicEditor is served from a python localhost server, but I was not able to reproduce it on [http://epiceditor.com](http://epiceditor.com).

Command line phrase used to create the webserver:
`$ python -m SimpleHTTPServer 8000`

**Comment by philipaconrad** [comment] 2012-08-11 07:19
I'll try doing a clean clone on EpicEditor tomorrow and see if it still happens.

**Comment by OscarGodson** [comment] 2012-08-11 15:00
That python server is how I do all my testing :) Yes, let me know if you can get a test case on JSBin so I can see what you mean and also work against.

**Comment by OscarGodson** [comment] 2012-08-13 03:24
Any luck? Since it's been around 48hrs I'm going to close this since I can't reproduce. Feel free to reopen if you can get a test case online I can see so I can test against it. Thanks!

**Closed as completed by OscarGodson** 2012-08-13 03:24 UTC
