### ISSUE TITLE
Â for every space at reload

### ISSUE THREAD

**Issue by MariusRumpf** [OscarGodson/EpicEditor#248] opened 2013-06-18 19:38 UTC
Browser: Chrome 27
System: OSX 10.8.3

```
<html>
<head>
    <title>Test Case</title>
    <script src="js/epiceditor.min.js"></script>
</head>
<body>
    <div id="epiceditor"></div>
    <script>var editor = new EpicEditor().load();</script>
</body>
</html>
```

Typed some text into the editor. 
![No reload](https://f.cloud.github.com/assets/2364426/670922/39dff482-d84e-11e2-87e9-6867207720b0.png)
body:`Some written text`

If I reload the page it adds an extra Â symbol for each space every time. After 5 reloads I would end up with something like this. 

![After 5 reloads](https://f.cloud.github.com/assets/2364426/670950/ed7bb404-d84e-11e2-8897-3222d4176a63.png)
body:`SomeÂÂÂÂÂ&nbsp;writtenÂÂÂÂÂ&nbsp;text`

**Comment by Gankra** [comment] 2013-06-18 20:27
If I head to guess, I'd bet it's because you're not setting your encoding to utf-8 via `<meta charset='utf-8'>`

If that doesn't fix it, what version of the editor are you using?

**Comment by Gankra** [comment] 2013-06-18 20:40
To be clear, does this reproduce for you on http://epiceditor.com ?

**Comment by OscarGodson** [comment] 2013-06-18 22:04
@Gankro I can reproduce this in the minified code with or without the meta tag, but not the unminified code. It'd be rad if you could take a look or have time. Unfortunately I can't right now :(

**Comment by Gankra** [comment] 2013-06-19 16:08
The issue is this line:

```
content = content.replace(/ /g, '\u00a0');
```

in _setText.

The minifier is replacing `'\u00a0'` with `" "`.

**Comment by OscarGodson** [comment] 2013-06-19 16:16
Dammit. I think I opened an issue about this before. I'll just manually put it back and push for a hot fix and figure out a "real" fix.

**Comment by OscarGodson** [comment] 2013-06-19 18:47
There's a PR in the queue now. efbd1bb should fix your problem. Feel free to pull down the PR and test it out or use it. Should be safe, but I think @Gankro will take a look at it before it hits master.

**Comment by Gankra** [comment] 2013-06-19 19:06
Fixed by #249

**Comment by Gankra** [comment] 2013-06-19 19:07
Note: if you make a change and rebuild, this issue may reappear in your .min.js. We should find a way to resolve this properly.

That said, I only use the .js for various reasons, so this isn't high on my todos.

**Closed as completed by Gankra** 2013-06-19 19:06 UTC
Labels: Bug, 0.2.1.1

**Comment by OscarGodson** [comment] 2013-06-19 19:47
Yep, I'm going to try upgrading uglify or look for another minifier this weekend. I'll need to run the specs against the new minifier / uglify upgrade too.
