### ISSUE TITLE
got undefined when exportFile version:0.2.1.1 

### ISSUE THREAD

**Issue by teamrun** [OscarGodson/EpicEditor#277] opened 2013-08-12 08:28 UTC
this happens occasionally： invoke exportFile method, and it returns undefined。

And then i try this method many times, appears that it return undefined every other time.

![epiceditor_exportfile_undefined](http://chenllos.com/src/img/epcieditor_undefined.png)

is it a bug? 

waiting for your reply。

**Comment by OscarGodson** [comment] 2013-08-12 09:26
Could you show me some of your code that is causing the undefined to appear so I can reproduce it?

**Comment by teamrun** [comment] 2013-08-14 07:04
here, i init epiceditor in html file: 

```
seajs.use("writer.js");
var editor = new EpicEditor().load();
```

then, i try to get editor's content after i write something in the it in writer.js. 

```
newBlog = editor.exportFile('html');
```

and the newBlog could be undefined...

**Comment by teamrun** [comment] 2013-08-14 07:06
sorry to reply so late

**Comment by OscarGodson** [comment] 2013-08-14 07:34
Hmm, well, `exportFile('html')` will try to export a file _named_ html as plain text. Is that what you have have and want or did you want the _current file_ to be exported as html? I assume that's what you wanted.

If you don't have a file named `html` it'll return undefined because there's no localStorage file with that name. If you just want the current file do:

``` js
editor.exportFile('myFileName', 'html');
```

You can do `null` if you don't know or care about the filename:

``` js
editor.exportFile(null, 'html');
```

I'm closing it for now since I assume this isn't a bug, you just were missing a param. If you're still having trouble reopen with more details :)

**Closed as completed by OscarGodson** 2013-08-14 07:34 UTC
