### ISSUE TITLE
Side by side view without full-screen.

### ISSUE THREAD

**Issue by oliverjanik** [OscarGodson/EpicEditor#274] opened 2013-08-01 06:28 UTC
Can EE by laid out with preview next to edit area without the need to click full-screen button or preview button?

**Comment by OscarGodson** [comment] 2013-08-01 20:02
Not by flipping an option on, but its easy setting it up: https://gist.github.com/OscarGodson/d58ef4994ee703ce6622

**Comment by oliverjanik** [comment] 2013-08-01 23:31
Thanks for the Gist. Are you planning a feature like that in future?

**Comment by OscarGodson** [comment] 2013-08-02 15:40
Yeah, it's been requested a few times so I'd like to. Closing this ticket since it's a dupe of https://github.com/OscarGodson/EpicEditor/issues/228

Thanks!

**Closed as completed by OscarGodson** 2013-08-02 15:40 UTC
