### ISSUE TITLE
Preview content not updated when autoSave disabled

### ISSUE THREAD

**Issue by mindscratch** [OscarGodson/EpicEditor#195] opened 2013-01-04 03:34 UTC
It appears with v0.1.1 and master (as of e2b9cd3649252e76b3dc94419ef378c53281f0e8) don't "save" the content before entering "preview" mode.

If you create an EpicEditor and set autoSave to false, then enter some content and click on the "preview" button, the content in "preview" mode will not be updated.

**Comment by daxxog** [comment] 2013-01-04 20:57
Confirmed, I am experiencing the same issue.

**Comment by OscarGodson** [comment] 2013-01-04 21:01
I see the problem. Might be a little tricky to fix after inspection. I'll need to have a "epiceditor-preview" storage bin and change up how the editor uses storage for private stuff.

**Comment by OscarGodson** [comment] 2013-01-09 09:35
@mindscratch @daxxog I've pushed a patch for this (014ccd1). Can you please checkout the branch "feature/ticket-195" and let me know if this fixes your problem? I'd also be interested on if you think the patch is OK code wise. Feels kinda hacky, but not sure if I know a better way. 

If it looks good I'll probably write some tests and merge it into develop.

**Comment by mindscratch** [comment] 2013-01-09 13:21
I'll take a look this evening (i'm US EST).

**Comment by daxxog** [comment] 2013-01-09 14:47
@OscarGodson I checked out your branch and modified 

```
67c67
<     autoSave: 100
---
>     autoSave: false
```

in index.html

Everything seems to work now!

Thanks :smile:

**Comment by OscarGodson** [comment] 2013-01-09 16:49
@daxxog :thumbsup:

**Comment by mindscratch** [comment] 2013-01-10 00:28
@OscarGodson I do see a bit of hacky-ness creeping in, especially since the new "isPreviewDraft" flag is found its way into several places. For now I think it's ok, but it would probably be worthwhile revisiting in the future. Thanks for resolving this, seems to be working for me.

**Comment by OscarGodson** [comment] 2013-01-10 00:32
Alright, if everything seems to be working ill add a test or two and merge this one in. Thanks for the report and email!

**Comment by OscarGodson** [comment] 2013-01-10 09:26
OK, test in. Closing ticket. Thanks guys!

**Closed as completed by OscarGodson** 2013-01-10 09:26 UTC
Labels: Important, Bug, 0.2.1, QA'd
